### ISSUE TITLE
Unable to login with Ionic in IOS mobile simulator 

### ISSUE THREAD

**Issue by grajuu** [mraible/mobile-jhipster#8]
Unable to login with Ionic in IOS mobile simulator.
I have added the CORS

```
jhipster:
  clientApp:
    name: 'realThoughtApp'
  # By default CORS is disabled. Uncomment to enable.
  cors:
    allowed-origins: 'http://localhost:8100,http://localhost:9000,capacitor://localhost'
    allowed-methods: '*'
```

Error : Safari cannot open the page because the address is invalid.

![image](https://user-images.githubusercontent.com/44188062/124871462-b4ddc300-dfe1-11eb-8c4c-61fb0a43f7d8.png)
